name: Publish Images (GHCR)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # v로 시작하는 태그 push 시 릴리스 빌드

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi services)
        run: |
          set -e
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          SHORT_SHA=${GITHUB_SHA::7}
          for SVC in vision coach yt_ingest; do
            docker buildx build $SVC \
              -t ghcr.io/${REPO_LC}/$SVC:latest \
              -t ghcr.io/${REPO_LC}/$SVC:${SHORT_SHA} \
              --push
          done
